package dev.kuch.termx.core.data.db

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import dev.kuch.termx.core.data.db.converter.Converters
import dev.kuch.termx.core.data.db.dao.KeyPairDao
import dev.kuch.termx.core.data.db.dao.ServerDao
import dev.kuch.termx.core.data.db.dao.ServerGroupDao
import dev.kuch.termx.core.data.db.entity.KeyPairEntity
import dev.kuch.termx.core.data.db.entity.ServerEntity
import dev.kuch.termx.core.data.db.entity.ServerGroupEntity

/**
 * Single Room database for the app — `termx.db`.
 *
 * Schema export is on so migrations from version 1 onward are reviewable
 * in source control. The first emitted JSON (`schemas/.../1.json`) is
 * generated by CI and committed as a follow-up (task #51).
 */
@Database(
    entities = [
        ServerEntity::class,
        KeyPairEntity::class,
        ServerGroupEntity::class,
    ],
    version = 1,
    exportSchema = true,
)
@TypeConverters(Converters::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun serverDao(): ServerDao
    abstract fun keyPairDao(): KeyPairDao
    abstract fun serverGroupDao(): ServerGroupDao
}
